---
- name: Ensure Minecraft server is running
  hosts: localhost
  tasks:
    - name: Check if Minecraft server is running
      shell: ps aux | grep -v grep | grep minecraft
      register: minecraft_process
      ignore_errors: yes

    - name: Start Minecraft server if not running
      shell: java -Xmx1024M -Xms1024M -jar server.jar nogui
      when: minecraft_process.rc != 0
