---
- name: Ensure Minecraft server is running
  hosts: all
  become: yes
  tasks:
    - name: Ping the instance to ensure it is up and running
      ping:

    - name: Check if Minecraft server process is running
      shell: pgrep -f minecraft
      register: minecraft_process
      ignore_errors: yes

    - name: Ensure Minecraft server is running
      fail:
        msg: "Minecraft server is not running!"
      when: minecraft_process.rc != 0
