---
- name: Install Java and set up Minecraft server
  hosts: minecraft_servers
  become: yes

  tasks:
    - name: Download Java
      yum:
        name: java-17-amazon-corretto-headless
        state: present

    - name: Create Minecraft user
      user:
        name: minecraft

    - name: Create Minecraft server directory
      file:
        path: /opt/minecraft/server
        state: directory
        owner: minecraft
        group: minecraft

    - name: Download Minecraft server jar file
      get_url:
        url: "{{ minecraft_server_url }}"
        dest: /opt/minecraft/server/server.jar
        mode: '0644'
        owner: minecraft
        group: minecraft

    # Add more tasks here for setting up Minecraft server
