name: Provision and Configure Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize Terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve -var="key_name=lab6"  
        terraform output -json | jq -r '.instance_ip.value' > ../terraform/instance_public_ip.txt
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Print instance public IP
      run: |
        cat terraform/instance_public_ip.txt

      
    #- name: Setup Ansible
    #  run: |
    #    sudo apt update
    #    sudo apt install -y ansible


    - name: Run Ansible playbook
      run: |
        INSTANCE_IP=$(cat terraform/instance_public_ip.txt)
        echo "[minecraft_server]" > ansible/terraform-inventory
        echo "$INSTANCE_IP ansible_ssh_private_key_file=${{ secrets.SSH_PRIVATE_KEY }} ansible_user=ec2-user" >> terraform/terraform-inventory
        ansible-playbook -i ansible/terraform-inventory ansible/playbook.yml -vvvv
      env:
        MINECRAFTSERVERURL: "https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Check Minecraft server with nmap
      run: |
        sudo apt update && sudo apt install -y nmap
        INSTANCE_IP=$(cat terraform/instance_public_ip.txt)
        nmap -sV -Pn -p T:25565 $INSTANCE_IP
