name: Provision and Configure Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start EC2 Instance
      run: |
        INSTANCE_ID=i-0ba311bacff7784d4
        aws ec2 start-instances --instance-ids $INSTANCE_ID
        aws ec2 wait instance-running --instance-ids $INSTANCE_ID
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Get Instance Public IP
      id: public_ip
      run: |
        INSTANCE_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
        echo "::set-output name=public_ip::$INSTANCE_IP"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Create Ansible Inventory
      run: |
        echo "[minecraft_server]" > inventory
        echo "${{ steps.public_ip.outputs.public_ip }} ansible_user=ec2-user" >> inventory

    - name: Setup Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible playbook
      run: ansible-playbook -i inventory ansible/playbook.yml
