name: Provision and Configure Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform

    - name: Apply Terraform
      run: |
        cd terraform
        terraform apply -auto-approve -var="key_name=minecraft_key.pem"

    - name: Setup Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible playbook
      run: ansible-playbook -i terraform/terraform-inventory ansible/playbook.yml
      env:
        MINECRAFTSERVERURL: "https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14e"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
