name: Provision and Configure Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-west-2

    - name: Check and delete existing key pair
      run: |
        KEY_NAME="minecraft-key"
        if aws ec2 describe-key-pairs --key-name $KEY_NAME > /dev/null 2>&1; then
          echo "Key pair $KEY_NAME exists. Deleting..."
          aws ec2 delete-key-pair --key-name $KEY_NAME
        else
          echo "Key pair $KEY_NAME does not exist. Proceeding..."
        fi

        
    - name: Initialize Terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
        terraform output -raw private_key > ../terraform/minecraft_key.pem
        terraform output -json | jq -r '.instance_ip.value' > ../terraform/instance_public_ip.txt
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-west-2  # 원하는 리전을 여기에 명시합니다.
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        cp ./terraform/minecraft_key.pem ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Create Ansible inventory
      run: |
        INSTANCE_IP=$(cat terraform/instance_public_ip.txt)
        echo "[minecraft]" > ansible_hosts
        echo "$INSTANCE_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ansible_hosts

    - name: Display Ansible inventory
      run: cat ansible_hosts

    - name: Run Ansible playbook
      run: ansible-playbook -i ansible_hosts ansible/playbook.yml

    - name: Check Minecraft server with nmap
      run: |
        sudo apt update && sudo apt install -y nmap
        INSTANCE_IP=$(cat terraform/instance_public_ip.txt)
        sleep 15
        nmap -sV -Pn -p T:25565 $INSTANCE_IP
