name: Provision and Configure Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Start EC2 Instance
      run: |
        INSTANCE_ID=$(jq -r '.instance_id.value' terraform/tf-outputs.json)
        aws ec2 start-instances --instance-ids $INSTANCE_ID
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Setup Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Create SSH Key File
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa


    - name: Create Ansible Inventory
      run: |
        INSTANCE_IP=$(jq -r '.instance_ip.value' terraform/tf-outputs.json)
        echo "[minecraft_server]" > inventory
        echo "$INSTANCE_IP ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_user=ec2-user" >> inventory

    - name: Run Ansible playbook
      run: ansible-playbook -i inventory ansible/playbook.yml
